@startuml C4_Level2
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Diagrama de Container - Pipes and Filters

Person(user, "Usuário", "Cliente API / Frontend")

System_Boundary(c1, "Image Processing Pipeline") {
    Container(preprocessing, "Preprocessing Filter", "NestJS", "Recebe a imagem crua, valida e normaliza.")
    Container(transformation, "Transformation Filter", "NestJS", "Aplica filtros, redimensionamento ou conversão.")
    Container(ai, "AI Filter", "NestJS", "Aplica modelos de ML para análise ou geração.")
}

Rel(user, preprocessing, "1. Envia Imagem", "HTTP/REST")
Rel(preprocessing, transformation, "2. Dados Normalizados", "Async Msg / HTTP")
Rel(transformation, ai, "3. Dados Transformados", "Async Msg / HTTP")
Rel(ai, user, "4. Retorna Resultado (ou via Webhook)", "HTTP")

@enduml