@startuml C4_Level3
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Diagrama de Componente - AI Filter (Microserviço)

Container(transf_app, "Transformation Filter", "NestJS", "Origem dos dados")

Container_Boundary(ai_app, "AI Filter Application") {
    Component(appController, "App Controller", "NestJS Controller", "Recebe requisições de processamento de IA.")
    Component(appService, "App Service", "NestJS Service", "Contém a lógica de negócio e orquestra o modelo de IA.")
    Component(aiModel, "AI Logic/Model", "Lib/TensorFlow", "Executa a inferência real.")
}

Rel(transf_app, appController, "Envia solicitação", "DTO")
Rel(appController, appService, "Chama método de processamento")
Rel(appService, aiModel, "Executa inferência")
@enduml